apiVersion: v1
kind: PersistentVolume
metadata:
  name: rust-desk-pv
spec:
  capacity:
    storage: 11Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
  nfs:
    path: /var/nfsshare/rust-desk/data
    server: 192.168.12.56

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rust-desk-pvc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 11G

